### ISSUE TITLE
[Bug Report]: CustomModelData doesn't work

### ISSUE THREAD

**Issue by MelonHell** [Crazy-Crew/CrazyAuctions#157]
### Server Version

Paper 1.19.4 build 530

### Plugin Version

Crazy Auctions v1.2.19

### Describe the bug

```yml
      PreviousPage: #The button for Previous Page.
        Item: 'PAPER#10000'
        Toggle: true
        Slot: 49
        Name: '&6Previous Page'
        Lore: { }
```

![image](https://github.com/Crazy-Crew/CrazyAuctions/assets/53826469/d6643fd8-126d-45f6-9c4b-857e2a93ded9)

### Spark link

not required in this case

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by CrazyCrew.
